path: D:\TFM\YOLOv8\Data  # dataset root dir
train: images\train  # train images (relative to 'path')
val: images\val  # val images (relative to 'path')
test: images\test  # val images (relative to 'path')

# Classes
names:
  0: pigLying
  1: pigNotLying